# rustfmt doc - https://rust-lang.github.io/rustfmt/

hard_tabs = true
edition = "2021"

# For recording
max_width = 85
struct_lit_width = 40
# struct_variant_width = 40
chain_width = 50
# array_width = 40